### ISSUE TITLE
How to build those wasm files?

### ISSUE THREAD

**Issue by txchen** [lrusso/EmulatrixWeb#10]
Awesome project!
Do you mind sharing how to build js and wasm from libretro? Thanks a lot!

**Comment by lrusso** [comment]
Hello, I'm glad you like this project. 

Also, I didn't build the libretro cores, I used the files mentioned in the readme.md, but I modified the compiled code in each emulator in order to fix a bug that prevents the canvas from been resized.

For last, I modified the DOSBox compiled code because there was a bug where the emulator kept running when the browser tab was inactive/blur so after a while (20/30/60 minutes) you go back to that tab and the emulation got frozen. Now this bug was fixed and the emulation pauses when blur and resumes when focus. The others emulators in Emulatrix have the same behaviour.
